import { v4 as uuid } from 'uuid';
import {
  E1,
  E2,
  E3,
  E4,
  N1,
  N2,
  N3,
  N4,
  N5,
  N6,
  N7,
  N8,
  R1,
  R2,
  R3,
  R4,
  R5,
  R6,
  R7,
  R8,
  R9,
  W1,
  W2,
  W3,
  W4,
  W5,
  W6,
} from '../../assets';

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 2200,
    discount: '50%',
    categoryName: 'Wedding Sets',
    rating: 4.5,
    imgUrl: W1,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 2300,
    discount: '50%',
    categoryName: 'Wedding Sets',
    rating: 4,
    imgUrl: W2,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 2100,
    discount: '50%',
    categoryName: 'Wedding Sets',
    rating: 3,
    imgUrl: W3,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 2500,
    discount: '40%',
    categoryName: 'Wedding Sets',
    rating: 4,
    imgUrl: W4,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 1500,
    discount: '30%',
    categoryName: 'Wedding Sets',
    rating: 4,
    imgUrl: W5,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 2500,
    discount: '50%',
    categoryName: 'Wedding Sets',
    rating: 3.5,
    imgUrl: W6,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 1000,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 3,
    imgUrl: N1,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 2500,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 2.5,
    imgUrl: N2,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 1800,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 3,
    imgUrl: N3,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 1200,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 5,
    imgUrl: N4,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 1900,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 3.5,
    imgUrl: N5,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 2400,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 2,
    imgUrl: N6,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 2300,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 3.5,
    imgUrl: N7,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 2200,
    discount: '50%',
    categoryName: 'Necklace',
    rating: 4,
    imgUrl: N8,
  },

  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 1100,
    discount: '50%',
    categoryName: 'Rings',
    rating: 5,
    imgUrl: R1,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 1400,
    discount: '50%',
    categoryName: 'Rings',
    rating: 5,
    imgUrl: R2,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 1450,
    discount: '50%',
    categoryName: 'Rings',
    rating: 5,
    imgUrl: R3,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 1400,
    discount: '50%',
    categoryName: 'Rings',
    rating: 4,
    imgUrl: R4,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 1200,
    discount: '50%',
    categoryName: 'Rings',
    rating: 4,
    imgUrl: R5,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 1100,
    discount: '50%',
    categoryName: 'Rings',
    rating: 4,
    imgUrl: R6,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 1150,
    discount: '50%',
    categoryName: 'Rings',
    rating: 5,
    imgUrl: R7,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 2220,
    discount: '50%',
    categoryName: 'Rings',
    rating: 5,
    imgUrl: R8,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 1500,
    discount: '50%',
    categoryName: 'Rings',
    rating: 4,
    imgUrl: R9,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 1440,
    discount: '50%',
    categoryName: 'Earrings',
    rating: 4,
    imgUrl: E1,
  },
  {
    _id: uuid(),
    store: 'Tanishq Jewellers',
    price: 1000,
    discount: '70%',
    categoryName: 'Earrings',
    rating: 3,
    imgUrl: E2,
  },
  {
    _id: uuid(),
    store: 'Chandukaka Saraf Jewellers',
    price: 3000,
    discount: '20%',
    categoryName: 'Earrings',
    rating: 5,
    imgUrl: E3,
  },
  {
    _id: uuid(),
    store: 'Kalyan Jewellers',
    price: 3000,
    discount: '20%',
    categoryName: 'Earrings',
    rating: 3.5,
    imgUrl: E4,
  },
];
