export const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY';
export const FILTER_BY_RATING = 'FILTER_BY_RATING';
export const SORT_BY_PRICE = 'SORT_BY_PRICE';
export const FILTER_BY_PRICE_RANGE = 'FILTER_BY_PRICE_RANGE';
export const CLEAR_ALL_FILTER = 'CLEAR_ALL_FILTER';
